# Generated by Django 3.2.16 on 2022-11-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
