# Generated by Django 3.2.16 on 2022-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followers',
        ),
    ]
