# Generated by Django 3.2.16 on 2022-11-20 01:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(null=True, upload_to=core.models.user_header_image_file_path),
        ),
    ]
